const defaultPlants = [
  {
    id: "CY-001",
    name: "白粉彩叶芋",
    family: "彩叶芋",
    code: "CY",
    score: 9.0,
    personality: "热闹型、爆盆选手、长叶机器",
    stage: "稳定生长期",
    light: "明亮散射光 + 补光灯",
    watering: "保持微湿，后续建立湿度计数值",
    focus: "观察新叶大小、颜色是否稳定，避免暴晒和长期积水",
    note: "老叶轻微卷边属正常代谢",
    cover: ""
  },
  {
    id: "CY-002",
    name: "红叶彩叶芋",
    family: "彩叶芋",
    code: "CY",
    score: 9.8,
    personality: "精品贵妇、颜值担当",
    stage: "高速生长期",
    light: "明亮散射光 + 补光灯",
    watering: "水苔控水，掂重量判断",
    focus: "保持叶色饱和，观察新芽展开",
    note: "当前状态接近完美",
    cover: ""
  },
  {
    id: "CY-003",
    name: "白绿彩叶芋",
    family: "彩叶芋",
    code: "CY",
    score: 9.9,
    personality: "学霸型、稳定、镇宅大盆候选",
    stage: "旺盛生长期",
    light: "明亮散射光 + 补光灯",
    watering: "保持微湿但不积水",
    focus: "继续观察爆芽和新叶数量",
    note: "目前全家最佳状态之一",
    cover: ""
  },
  {
    id: "QH-001",
    name: "银叶秋海棠",
    family: "秋海棠",
    code: "QH",
    score: 8.8,
    personality: "傲娇小姐、恢复型",
    stage: "恢复生长期",
    light: "明亮散射光",
    watering: "微湿，不能长期湿",
    focus: "叶缘焦边、湿度、控水",
    note: "有新芽，说明根系还在恢复",
    cover: ""
  },
  {
    id: "QH-002",
    name: "波点秋海棠",
    family: "秋海棠",
    code: "QH",
    score: 9.5,
    personality: "阳光女孩、快速长高型",
    stage: "快速生长期",
    light: "明亮散射光",
    watering: "微湿，避免积水",
    focus: "后续可修剪扦插，让株型更丰满",
    note: "正在开花并持续长新叶",
    cover: ""
  },
  {
    id: "QH-003",
    name: "银脉秋海棠",
    family: "秋海棠",
    code: "QH",
    score: 9.5,
    personality: "高冷艺术家",
    stage: "青年分枝期",
    light: "明亮散射光",
    watering: "微湿，避免闷根",
    focus: "保持通风，观察分枝",
    note: "叶面银色状态优秀，叶背酒红",
    cover: ""
  },
  {
    id: "HY-001",
    name: "黑叶海芋（左）",
    family: "海芋",
    code: "HY",
    score: 9.2,
    personality: "成熟女王、稳重型",
    stage: "成熟爆盆期",
    light: "明亮散射光",
    watering: "见干见湿，避免积水",
    focus: "老叶黄化正常，重点看新叶和基部是否健康",
    note: "叶多且密，老叶代谢较明显",
    cover: ""
  },
  {
    id: "HY-002",
    name: "黑叶海芋（右）",
    family: "海芋",
    code: "HY",
    score: 9.8,
    personality: "王者型、气场担当",
    stage: "高速发育期",
    light: "明亮散射光",
    watering: "见干见湿，避免积水",
    focus: "保持空间，避免叶片互相挡光",
    note: "叶片挺立、叶脉清晰、状态优秀",
    cover: ""
  },
  {
    id: "LR-001",
    name: "柠檬心叶蔓绿绒",
    family: "蔓绿绒",
    code: "LR",
    score: 9.7,
    personality: "阳光小狗、乐天派",
    stage: "恢复后快速生长期",
    light: "中高亮散射光",
    watering: "可稍微干一点再浇",
    focus: "可换大一号盆，后续可修剪回插",
    note: "从软趴趴变得有韧劲，开始向上生长",
    cover: ""
  },
  {
    id: "LR-002",
    name: "水培裂叶蔓绿绒",
    family: "蔓绿绒",
    code: "LR",
    score: 8.5,
    personality: "打不死的小战士",
    stage: "恢复生长期",
    light: "明亮散射光，避免贴玻璃暴热",
    watering: "水培，定期换水",
    focus: "老叶焦边不用纠结，重点观察新叶是否健康",
    note: "历史焦边严重，但现在持续长新叶",
    cover: ""
  },
  {
    id: "GL-001",
    name: "银斑葛 / 银皇后绿萝",
    family: "葛类",
    code: "GL",
    score: 10,
    personality: "温柔小精灵、佛系但很能长",
    stage: "青年快速生长期",
    light: "中高亮散射光",
    watering: "可稍微干一点再浇",
    focus: "后续可爬杆或垂吊，叶片会继续变大",
    note: "银纹漂亮，新叶持续冒出",
    cover: ""
  },
  {
    id: "GY-001",
    name: "银纹观叶植物（疑似西瓜皮椒草）",
    family: "观叶植物",
    code: "GY",
    score: 8.0,
    personality: "慢热贵公子",
    stage: "恢复观察期",
    light: "明亮散射光，避免直吹风",
    watering: "控制浇水，避免闷根",
    focus: "当前最需要观察，重点看未来一个月新叶是否完整",
    note: "已加通气管改善闷根，开始长新叶",
    cover: ""
  }
];

const familyMeta = {
  CY: { name: "彩叶芋", color: "#f4ccd7" },
  QH: { name: "秋海棠", color: "#8d3e59" },
  HY: { name: "海芋", color: "#47795e" },
  LR: { name: "蔓绿绒", color: "#86b255" },
  GL: { name: "葛类", color: "#b4d4a8" },
  GY: { name: "观叶植物", color: "#a7afb5" }
};

module.exports = {
  defaultPlants,
  familyMeta
};
